version: "3"

services:
  app:
    container_name: app_processing
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8004:8000
    restart: always
